name: s2s_repro
channels:
  - pytorch
  - conda-forge
dependencies:
  - dask==2021.9.1
  - dask-jobqueue==0.7.3
  - mlflow==1.19.0
  - netcdf4==1.5.6
  - pandas==1.2.4
  - python==3.8.10
  - pytorch==1.8.1
  - xskillscore==0.0.21
  - pip
  - pip:
    - hydra-core==1.1.1
    - hydra-submitit-launcher==1.1.5
    - pytorch-lightning==1.4.8
