aggregated_obs:
  deterministic: ${base_dir}/hindcast-like_observations_2000-2019_biweekly_deterministic.nc
  terciled: ${base_dir}/hindcast-like_observations_2000-2019_biweekly_terciled.nc
  edges: ${base_dir}/hindcast-like-observations_2000-2019_biweekly_tercile-edges.nc
input:
  flat: ${base_dir}/training-input
  plev: ${base_dir}/training-input
last_forecast: "2019-11-20"
year:
file_label: "hindcast"
valid_threshold: "2020-01-01"
name: train