aggregated_obs:
  deterministic: ***BASEDIR***2/from-template-lfs/hindcast-like_observations_2000-2019_biweekly_deterministic.nc
  terciled: ***BASEDIR***2/from-template-lfs/hindcast-like_observations_2000-2019_biweekly_terciled.nc
  edges: ***BASEDIR***2/from-template-lfs/hindcast-like-observations_2000-2019_biweekly_tercile-edges.nc
input:
  flat: '***BASEDIR***training-input'
  plev: '***BASEDIR***processed/training-input'
last_forecast: "2019-11-20"
year:
file_label: "hindcast"
valid_threshold: "2020-01-01"