defaults:
  - model: emos_normalgamma
  - optimizer: adam
  - transform: emos_cube
  - module: tercile

hydra:
  job:
    name: S2S_BAYES
user: ${oc.env:USER}
dataset_dir: ***HOME***fast_scratch/s2s/mlready/2021-09-08-w-features
num_workers: ${oc.env:SLURM_CPUS_PER_TASK,4}
validate_from: 2018

# Config for lightning trainer.
trainer:
  accelerator: auto
  devices: 1
  max_epochs: 100
  accumulate_grad_batches: 1
  fast_dev_run: False
lr_find: False
include_features: True
early_stopping:
  patience: 5
index:
logging:
  experiment_name: "S2S_Bayes_2"
  run_name:
  mlflow_uri: "${oc.env:MLFLOW_TRACKING_URI,http://10.1.48.27:5000}"
  slurm_job_id: "${oc.env:SLURM_JOB_ID,null}"
  slurm_array_jobid: "${oc.env:SLURM_ARRAY_JOB_ID,null}"
  slurm_array_taskid: "${oc.env:SLURM_ARRAY_TASK_ID,null}"

weights_lr: 1e-6
model_lr: 1e-3