defaults:
  - experiment: bayes_conv
  - backend: singlegpu

hydra:
  job:
    name: S2S_TRAIN
  run:
    dir: ${oc.env:S2S_RUNS,.}/train/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:S2S_RUNS,.}/train/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Default values for the experiment. They are meant to be overridden by the
# experiment config group.
experiment:
  user: ${oc.env:USER}
  logging:
    experiment_name: "S2S_Bayes_3"
    run_name: "${hydra:runtime.choices.experiment}"
    mlflow_uri: "${oc.env:MLFLOW_TRACKING_URI,http://10.1.48.27:5000}"
    slurm_job_id: "${oc.env:SLURM_JOB_ID,null}"
    slurm_array_jobid: "${oc.env:SLURM_ARRAY_JOB_ID,null}"
    slurm_array_taskid: "${oc.env:SLURM_ARRAY_TASK_ID,null}"
  max_epochs: 100
  dataset:
    include_model: False

lr_find: False