defaults:
  - model: emos
  - optimizer: adam
  - transform: emos

batch_size: 8
dataset_dir: ***BASEDIR***/mlready/2021-08-08-test/
num_workers: ${oc.env:SLURM_CPUS_PER_TASK,4}
validate_from: 2018
accelerator: auto
devices:
max_epochs: 10
lr_find: False
index: