defaults:
  - set: train

base_dir: ***HOME***fast_scratch/s2s/repro


fields:
  u: 
    - 200
    - 850
  v:
    - 200
    - 850
  gh:
    - 1000
    - 500
    - 200
center: 'ecmwf'
n_workers: ${oc.env:SLURM_CPUS_PER_TASK,4}
overwrite: False