flat: '***BASEDIR***training-input'
plev: '***BASEDIR***processed/training-input'
obs_terciled: '***BASEDIR***/renku/hindcast-like-observations_2000-2019_biweekly_terciled.nc'
edges: '***BASEDIR***/edges/renku.nc'