_target_: crims2s.training.model.bayes.BayesianUpdateModel
forecast_model:
  _target_: crims2s.training.model.NormalCubeNormalMultiplexedEMOS
  biweekly: True
weight_model:
  _target_: crims2s.training.model.bayes.LinearWeightModel
  in_features: 14